# Generated by Django 4.2 on 2025-04-20 01:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "phone_num",
                    models.CharField(
                        default="0000000000", max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(max_length=100, verbose_name="Education Level"),
                ),
                (
                    "user_id",
                    models.CharField(
                        default=main.models.generate_unique_user_id,
                        max_length=8,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
