# Generated by Django 4.2 on 2025-04-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="register",
            name="education_level",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="register",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="phone_num",
            field=models.CharField(max_length=15),
        ),
    ]
