# Generated by Django 4.2 on 2025-04-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
    ]
