# Generated by Django 4.2 on 2025-04-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_event_slug"),
    ]

    operations = []
