# Generated by Django 4.2 on 2025-04-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_auto_20250429_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
