# Generated by Django 5.1.6 on 2025-04-30 23:14

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_form_question_response_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_id',
            field=models.CharField(default=main.models.generate_unique_user_id, max_length=20, unique=True),
        ),
    ]
