# Generated by Django 4.2 on 2025-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_register_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="materials/")),
                (
                    "material_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("audio", "صوت"), ("video", "فيديو")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
